version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install production dependencies
          command: |
            composer validate
            composer install --no-dev -o
      - persist_to_workspace:
          root: .
          paths:
            - vendor
  php_lint:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Composer dependencies
          command: |
            composer validate
            composer install --prefer-dist
  build-main:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "d6:de:ae:4c:83:8b:ed:b5:ed:22:13:be:c2:d3:4b:cb"
      - deploy:
          name: Deploy -built branch to github
          command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
# Orchestrate our job run sequence.
workflows:
  version: 2
  build_and_test:
    jobs:
      - php_lint:
          filters:
            branches:
              ignore: /.*-built/
      - build:
          requires:
            - php_lint
      - build-main:
          requires:
            - build
